// ══════════════════════════════════════════════════════════════════════
// Firebase configuration — ported directly from src/firebase-config.js.
// Same Firebase project as the existing Capacitor app: asf-app-2990c.
//
// NOTE: this file was hand-written (not generated by `flutterfire configure`,
// since this environment has no Flutter/FlutterFire CLI access). The
// Android values below are copied from the existing
// android/app/google-services.json / src/firebase-config.js. If you have
// the FlutterFire CLI available, running `flutterfire configure` against
// the same Firebase project (asf-app-2990c) will regenerate this file more
// robustly (and add iOS values, which aren't ported here since the
// existing app's SETUP.md/firebase-config.js only ever populated web/
// Android values). Until then, this file covers Android, which is this
// project's only real target platform so far.
// ══════════════════════════════════════════════════════════════════════

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions has not been configured for platform '
          '${defaultTargetPlatform.name} yet — this project has only been '
          'set up for Android so far. Run `flutterfire configure` to add '
          'iOS/other platforms against the asf-app-2990c Firebase project.',
        );
    }
  }

  // Values copied 1:1 from the existing project's android/app/google-services.json
  // (the Android-specific client entry, not the web one used by src/firebase-config.js —
  // Android's app id / api key are different from the web app's).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCADEBRnmQe-yBFg1syGVY_J3aAnE9leHg',
    appId: '1:661869403000:android:039312ef925f88f56e068d',
    messagingSenderId: '661869403000',
    projectId: 'asf-app-2990c',
    storageBucket: 'asf-app-2990c.firebasestorage.app',
  );
}
